---
title: "Multilevel Machine Learning"
subtitle: "Random Effekts for Black Box Models"
author: "Aaron Peikert"
date: "`r Sys.Date()`"
bibliography: MA.bib
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require("pacman"))install.packages("pacman")
pacman::p_load("tint", "here", "tidyverse")
```

The usual target of statistical modelling in psychologie are new samples, but such approach does severly limit what psychologists can attempt to study. Stemming from @cattellDataBox1988 idea of the "data box", several authors [e.g. @nesselroadeBehavioralScienceMeasurement2016; @revelleDataBoxSubject2016; @revelleModelPersonalityThree2015] argue that the individual should be the main focus of the analysis. That means generalising not to new individuals, but to the behavior of the same individuals at a later timepoint. The attempt of using statistical models, that are not specifically designed for such enduver, makes the assumption that condtional on the measured features all individuals are in fact interchangeable. This assumption can rarely be justified in psychological research.

Imagine a teacher is rated by his students and we set out to predict the  students rating of the next lesson with the past lessons rating. Two approaches come to mind, either we predict each students rating by his individual rating or we predict each students rating by the overall average of the students. The one makes the assumption that there is nothing to learn from the other students ratings, the other that there is nothing to learn from the individual beyond representing a sample of the population. Each assumption represents historically important lines of psycholigical research, namely experimental and differential psychologie. If we had a large sample of each students ratings, reagardless of which assumption is true, predicting the individual rating by past ratings of the individual would perform always better. So why is it that we often choose to model the individual by some sort of average of the population? Because a lot of statistical precision can be gained, by making this simplifing assumption, since there is much more information about the population than about the individual.

While there is much research devoted to mixed effect models resulting in elegant solutions to problems such as the above, it is primarily focused on providing undbiased estimates instead of predictive accuracy and require a lot of thought from the researcher. It might be a fruitfull approach to fit abitrary predictive models simutanisly on the individual and the population and estimate on a per individual basis a mixture of there predictions.

# References
